name: Delete NPM tag on Branch Deletion
on: delete

env:
  CI_TOOLS_VERSION: '^4.2.0'

jobs:
  delete_npm_tag_for_branch:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: |
          echo "Delete NPM Tag for branch ${{ github.event.ref }}"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install CI Tools
        run: npm i -g @5minds/product_ci_tools@${{ env.CI_TOOLS_VERSION }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Delete npm tag
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_BRANCH: ${{ github.event.ref }}
        run: ci_tools delete-npm-tag --except-on-primary-branches
