on:
  release:
    types: [published, unpublished]

jobs:
  upload_download_sites_to_azure:

    name: Generate Download Site with Products and upload them to Azure
    runs-on: ubuntu-20.04

    steps:
      - name: "Use node"
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: "Install Download Site plugin"
        run: npm i -g @atlas-engine/atlasdownloadsite

      - name: "Create static html files in outputfolder"
        run: atlasdownloadsite
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload build artifacts
        uses: azure/cli@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage blob upload-batch \
              --account-name 5mindsproducts \
              --auth-mode login \
              --destination '$web' \
              --source output
